theme: jekyll-theme-midnight
title: "Dynatrace RUM — React Native Instrumentation Guide"
description: "De Automático a 100% Customizado: Referência Técnica para SRE & Mobile Engineers"
author: "Alan Delcaro"
github:
  repository_url: https://github.com/alan-delcaro/react_app
  issues_url: https://github.com/alan-delcaro/react_app/issues

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
